database=mysql
spring.datasource.url=jdbc:mysql://user07-db-mysql.c364s64uke8f.us-west-2.rds.amazonaws.com:3306/petclinic
spring.datasource.username=admin
spring.datasource.password=admin123!
spring.sql.init.mode=always
