apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
  namespace: petclinic

spec:
  replicas: 2
  selector:
    matchLabels:
      app: petclinic

  template:
    metadata:
      labels:
        app: petclinic

    spec:
      containers:
      - name: petclinic
        image: 450444046629.dkr.ecr.us-west-2.amazonaws.com/user07-petclinic:12
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

        env:
        - name: MYSQL_URL
          value: jdbc:mysql://user07-db-mysql.c364s64uke8f.us-west-2.rds.amazonaws.com:3306/petclinic

        - name: MYSQL_USER
          value: admin

        - name: MYSQL_PASSWORD
          value: admin123!
